compilers:
  - name: "gcc"
    version: "4.8"
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=ON -DREGRESSION_BASELINE_PATH:PATH=$REGERSSION_BASELINE -DREGRESSION_SCRIPT_PATH:PATH=$REGRESSION_DIR
  - name: cppcheck
    compiler_extra_flags: --enable=warning  --suppress="*:*gtest*" --suppress="constStatement:*Objex*" --suppress="cppcheckError:*" --suppress="uninitvar:*"
