compilers:
  - name: clang
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=ON -DREGRESSION_BASELINE_PATH:PATH=$REGERSSION_BASELINE -DREGRESSION_SCRIPT_PATH:PATH=$REGRESSION_DIR
  - name: clang
    build_type: Debug
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=ON -DREGRESSION_BASELINE_PATH:PATH=$REGERSSION_BASELINE -DREGRESSION_SCRIPT_PATH:PATH=$REGRESSION_DIR



