compilers:
  - name: Visual Studio
    version: 12
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=ON -DREGRESSION_BASELINE_PATH:PATH=%REGERSSION_BASELINE% -DREGRESSION_SCRIPT_PATH:PATH=%REGRESSION_DIR%
  - name: Visual Studio
    version: 12
    architecture: Win64
    cmake_extra_flags: -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=ON -DREGRESSION_BASELINE_PATH:PATH=%REGERSSION_BASELINE% -DREGRESSION_SCRIPT_PATH:PATH=%REGRESSION_DIR%


