site_name: EnergyPlus Documentation
site_favicon: favicon.ico
site_logo: 'EP_32x32.png'
repo_url: https://github.com/NREL/EnergyPlus

pages:
- [index.md, "Home"]
- [GettingStarted/GettingStarted.md, "Intro & Application", "Getting Started"]
- [Tips_and_Tricks_Using_EnergyPlus/Tips_and_Tricks_Using_EnergyPlus.md, "Intro & Application", "Tips and Tricks for EnergyPlus"]
- [EMS_Application_Guide/EMS_Application_Guide.md, "Intro & Application", "EMS Applications"]
- [ExternalInterfaces_Application_Guide/ExternalInterfaces_Application_Guide.md, "Intro & Application", "External Interface Applications"]
- [PlantApplicationGuide/PlantApplicationGuide.md, "Intro & Application", "Plant Applications"]
- [InputOutputReference/01-Page1.md, "Input/Output Reference", "Status"]
- [EngineeringReference/01-Overview.md, "Engineering Reference", "Overview"]
- [EngineeringReference/02-IntegratedSolution.md, "Engineering Reference", "Integrated Solution Manager"]
- [EngineeringReference/03-SurfaceHeatBalance.md, "Engineering Reference", "Surface Heat Balance Manager"]
- [EngineeringReference/04-AdvancedSurface.md, "Engineering Reference", "Advanced Surface Concepts"]
- [EngineeringReference/05-Climate.md, "Engineering Reference", "Climate, Sky and Solar Calculation"]
- [EngineeringReference/06-SolarRadiation.md, "Engineering Reference", "Solar Reflection"]
- [EngineeringReference/07-Daylighting.md, "Engineering Reference", "Daylighting and Window Calcs"]
- [EngineeringReference/08-AirHeatBalance.md, "Engineering Reference", "Air Heat Balance Manager"]
- [EngineeringReference/09-BuildingSystemSimulation.md, "Engineering Reference", "Building System Simulation Manager"]
- [EngineeringReference/10-Sizing.md, "Engineering Reference", "Sizing and Design Data"]
- [EngineeringReference/11-OperationalFaults.md, "Engineering Reference", "Operational Faults"]
- [EngineeringReference/11-DemandLimiting.md, "Engineering Reference", "Demand Limiting"]
- [EngineeringReference/12-AlternativeModeling.md, "Engineering Reference", "Alternative Modeling Processes"]
- [EngineeringReference/13-EncylopaedicRefs.md, "Engineering Reference", "Models - Encyclopedic Reference"]
- [EngineeringReference/14-OnSiteGeneration.md, "Engineering Reference", "On-SIte Generation"]
- [EngineeringReference/15-PerformanceCurves.md, "Engineering Reference", "Performance Curves and Lookup Tables"]
- [EngineeringReference/16-Economics.md, "Engineering Reference", "Economic Calculations"]
- [EngineeringReference/17-SpecialModulesReporting.md, "Engineering Reference", "Special Modules and Reporting"]
- [InterfaceDeveloper/InterfaceDeveloper.md, "Developer Guides", "Interface Developer"]
- [ModuleDeveloper/ModuleDeveloper.md, "Developer Guides", "Module Developer"]
- [Acknowledgements/Acknowledgments.md, "Other", "Acknowledgements"]
- [AuxiliaryPrograms/AuxiliaryPrograms.md, "Other", "Auxiliary Programs"]
- [OutputDetailsAndExamples/OutputDetailsAndExamples.md, "Other", "Output Details and Examples"]
- [Using_EnergyPlus_for_Compliance/Using_EnergyPlus_for_Compliance.md, "Other", "Using E+ for Compliance"]

theme: simplex
theme_dir: 'bootstrap_nrel'



