name: Build wheels

on:
  push:
    branches: [ develop ]

  # run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: false


jobs:
  build_wheel:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest, macos-latest, windows-2019]

    steps:
    - name: Checkout pyenergyplus
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: build wheels
      run: |
        pip install wheel
        python setup.py bdist_wheel

    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist
