name: CppCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout EnergyPlus
      uses: actions/checkout@v3

    - name: Install CppCheck
      run: sudo apt-get install cppcheck

    - name: Run CppCheck
      run: |
         cppcheck -UEP_Count_Calls -DEP_NO_OPENGL -UGROUND_PLOT -DLINK_WITH_PYTHON -DMSVC_DEBUG -DSKYLINE_MATRIX_REMOVE_ZERO_COLUMNS -U_OPENMP -Ugeneratetestdata \
          -DEP_cache_GlycolSpecificHeat -DEP_cache_PsyTsatFnPb -UEP_nocache_Psychrometrics -UEP_psych_errors -UEP_psych_stats  \
          --force \
          --std=c++17 \
          --enable=all \
          -i EnergyPlus/DXCoils.cc \
          -i EnergyPlus/RefrigeratedCase.cc \
          -i EnergyPlus/SolarShading.cc \
          -j $(nproc) \
          --template='[{file}:{line}]:({severity}),[{id}],{message}' \
          --suppress="uninitvar:*" \
          --cppcheck-build-dir=cppcheck-build-dir \
          ./src \
          3>&1 1>&2 2>&3 | tee cppcheck.txt

    - name: Parse and colorize cppcheck
      shell: bash
      run: python ./scripts/dev/colorize_cppcheck_results.py

    - name: Upload cppcheck results as artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
          name: EnergyPlus-${{ github.sha }}-cppcheck_results.txt
          path: cppcheck.txt
